version: '3.8'
services:
  api:
    container_name: github_api_proxy_node
    restart: on-failure
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    command: >
      sh -c "npm run start"
